name: 'Cloud Run Deploy and Docker Build'

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: 'vigilant-guru-449011-m1'
  REGION: 'asia-south1'
  SERVICE: 'study'
  REGISTRY: 'ghcr.io'
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/110187298432/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'my-service-account@vigilant-guru-449011-m1.iam.gserviceaccount.com'

      - name: Check Google Cloud authentication
        run: |
          gcloud config list
          gcloud auth list

      - name: Configure Docker
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev

      # (Rest of your steps remain unchanged)
