name: Deploy to Cloud Run

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: sreecharan1234/speakx-devops-assignment-lpu-a2026
  PROJECT_ID: "vigilant-guru-449011-m1"

on:
  schedule:
    - cron: '33 0 * * *'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest -f Dockerfile.prod .
          echo "Docker build completed successfully." # Print statement after build
          docker images # List built images for debugging

      - name: Push Docker Image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          echo "Docker push completed successfully." # Print statement after push
          docker images # List images after the push (should be empty locally)

      - name: Deploy to Cloud Run
        run: |
          SERVICE_NAME=your-service-name
          gcloud run deploy $SERVICE_NAME \
            --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            --platform managed \
            --region asia-south1 \
            --allow-unauthenticated
          echo "Cloud Run deployment completed successfully." # Print statement after deployment