# Combined Workflow: Deploy to Cloud Run and Build Docker Images

name: 'Cloud Run Deploy and Docker Build'

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  schedule:
    - cron: '25 8 * * *'
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: 'vigilant-guru-449011-m1' # TODO: update to your Google Cloud project ID
  REGION: 'asia-south1' # TODO: update to your region
  SERVICE: 'study' # TODO: update to your service name
  REGISTRY: ghcr.io # Use docker.io for Docker Hub if empty
  IMAGE_NAME: ${{ github.repository }} # github.repository as <account>/<repo>

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Docker: Set up Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      # Docker: Log into the registry
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Docker: Extract metadata for the image
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Docker: Build and push the image
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Docker: Sign the image (except for pull requests)
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      # Google Cloud: Authenticate using Workload Identity Federation
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider' # TODO: replace with your workload identity provider

      # Google Cloud: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          source: './'

      # Output the Cloud Run URL
      - name: Show Cloud Run URL
        run: echo ${{ steps.deploy.outputs.url }}
